### ISSUE TITLE
The heroku moodle instance uses a WorkHands-owned AWS bucket

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/moodle#3]

**Comment by erazorbg** [comment]
I need the folowing 3 items to setup Moodle to use your AWS bucket

1. AWS Access Key
2. AWS Access Secret
3. S3 Bucket name

Heroku documentation links to this article on how to generate an AWS key/secret pair:
https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys

**Comment by Pcushing** [comment]
@erazorbg i *think* i have an IAMUser set up with only access to the S3 bucket you need. Let me know if this works as expected.

1, 2 can both be acquired here. Let me know when you have it, and i'll remove this file:
https://www.dropbox.com/s/u35gpugqtgdxk30/nfcap-lms-keys.rtf?dl=0

3 is nfcap-lms

I only gave the IAMUser programmatic user, but if you need to get into the AWS console at all, let me know.

**Comment by erazorbg** [comment]
I have updated the configuration with the keys you provided, and it appears to be working. 

Let me know if you can see new files created in the bucket, the filenames are all hashes. There should be some new folders with 2 character names. 

Also for documentation purposes it turns out there was a 4th item needed, the AWS Region, which in this case is `us-west-1`

I have some ideas to setup this using environment variables from Heroku, I'll keep this open until I have it done.

**Comment by Pcushing** [comment]
Cool. I can see data in the bucket and just confirmed that some newly added SCORM files were added within a few minutes, too. Closing...
